on: [push]

env:
  GHCR_TOKEN: ${{ secrets.GHCR_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Docker build
        run: docker build --rm=false -t ghcr.io/tomas-rojo/flask-hello-world:0.0.1 .
      - name: Docker login
        run: echo $GHCR_TOKEN | docker login ghcr.io -u tomas-rojo --password-stdin
      - name: Docker push
        run: docker push ghcr.io/tomas-rojo/flask-hello-world:0.0.1
      - name: Install and configure the Koyeb CLI
        uses: koyeb-community/install-koyeb-cli@v2
        with:
          api_token: "${{ secrets.KOYEB_TOKEN }}"
          github_token: "${{ secrets.GITHUB_TOKEN }}"
      - name: Deploy to Koyeb
        run: koyeb service redeploy silly-jacinda/flask-koyeb
