name: "Build & Deploy"
on:
  workflow_run:
    workflows: ["Run Tests"]
    branches: [main]
    types: 
      - completed

jobs:
  setup-buildx:
    name: Set up Docker Buildx
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        id: set-matrix
        uses: docker/setup-buildx-action@v3

  build-and-push:
    name: Build and push Docker image
    needs: setup-buildx
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: [linux/amd64, linux/arm64]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: ${{ matrix.platform }}
          push: true
          tags: ghcr.io/${{ github.repository }}:${{ matrix.platform }}
          cache-from: type=gha
          cache-to: type=gha,mode=max


  # deploy:
  #    needs: build-and-push
  #    runs-on: ubuntu-latest
  #    steps:
  #     - name: Install and configure the Koyeb CLI
  #       uses: koyeb-community/install-koyeb-cli@v2
  #       with:
  #         api_token: "${{ secrets.KOYEB_TOKEN }}"
  #         github_token: "${{ secrets.GITHUB_TOKEN }}"

  #     - name: Deploy to Koyeb
  #       run: koyeb service redeploy silly-jacinda/flask-koyeb
