on: [push]

env:
  GHCR_TOKEN: ${{ secrets.GHCR_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Docker login
        run: echo $GHCR_TOKEN | docker login ghcr.io -u ${{ github.repository_owner }} --password-stdin

      - name: Docker build
        env:
          IMAGE_NAME: flask-hello-world
          TAG: latest
        run: |
          docker buildx build \
          --platform linux/amd64,linux/arm64 \
          -t ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:${{ env.TAG }} \
          --push .
